const {test}=require('node:test');const assert=require('node:assert/strict');const vm=require('node:vm');const fs=require('node:fs');
const source=fs.readFileSync('learning-storage.js','utf8');
function env(local={},durable={}){
 const map=new Map(Object.entries(local)),notices=[];let failKey=null;
 const storage={get length(){return map.size},key:i=>[...map.keys()][i],getItem:k=>map.get(k)??null,setItem(k,v){if(k===failKey){const e=new Error('quota');e.name='QuotaExceededError';throw e}map.set(k,String(v))},removeItem:k=>map.delete(k)};
 const db={objectStoreNames:{contains:()=>true},close(){},transaction(name,mode){const tx={objectStore(){return {get(){const r={};queueMicrotask(()=>{r.result=durable.snapshot; r.onsuccess()});return r},put(value){queueMicrotask(()=>{durable.snapshot=structuredClone(value);tx.oncomplete()})},delete(){queueMicrotask(()=>{delete durable.snapshot;tx.oncomplete()})}}}};return tx}};
 const doc={body:{appendChild:n=>notices.push(n)},head:{appendChild(){}},getElementById:id=>notices.find(n=>n.id===id),createElement:()=>({style:{},setAttribute(){}}),addEventListener(){}};
 const ctx={localStorage:storage,indexedDB:{open(){const r={};queueMicrotask(()=>{r.result=db;r.onsuccess()});return r}},document:doc,navigator:{},matchMedia:()=>({matches:false}),sessionStorage:{getItem:()=>null},addEventListener(){},setInterval(){},console,Date,JSON,Promise};ctx.window=ctx;vm.createContext(ctx);vm.runInContext(source,ctx);
 return {api:ctx.TopikLearningStorage,storage,map,durable,notices,setFail:k=>failKey=k};
}
const fixture={studyCount:'12',best_ch1:'5',topikVocabState:JSON.stringify({words:{v1:{correct:3,wrong:1}},sessions:{},history:{}}),topikExamResults:JSON.stringify({version:1,goal:80,records:[{id:'mock1',listening:60,reading:70}]})};
test('answers, vocabulary and mock results survive reopening',async()=>{const durable={},a=env({},durable);await a.api.ready;for(const[k,v]of Object.entries(fixture))a.storage.setItem(k,v);await a.api.syncNow();const b=env(Object.fromEntries(a.map),durable);await b.api.ready;for(const[k,v]of Object.entries(fixture))assert.equal(b.storage.getItem(k),v)});
test('IndexedDB restores records after localStorage is lost',async()=>{const durable={snapshot:{items:fixture}},a=env({},durable);await a.api.ready;for(const[k,v]of Object.entries(fixture))assert.equal(a.storage.getItem(k),v)});
test('corrupt local JSON recovers from snapshot',async()=>{const a=env({topikExamResults:'{broken'},{snapshot:{items:fixture}});await a.api.ready;assert.equal(a.storage.getItem('topikExamResults'),fixture.topikExamResults)});
test('backup round trip preserves all learning fields and ignores other storage',async()=>{const a=env({...fixture,unrelated:'keep'});await a.api.ready;const backup=await a.api.createBackup();assert.equal(backup.storage.unrelated,undefined);const b=env();await b.api.ready;await b.api.importBackup(backup);for(const[k,v]of Object.entries(fixture))assert.equal(b.storage.getItem(k),v)});
test('reset clears primary and reserve records without resurrection',async()=>{const durable={},a=env({...fixture,unrelated:'keep'},durable);await a.api.ready;await a.api.clearAll();const b=env(Object.fromEntries(a.map),durable);await b.api.ready;assert.equal(b.storage.getItem('studyCount'),null);assert.equal(b.storage.getItem('topikExamResults'),null);assert.equal(b.storage.getItem('unrelated'),'keep')});
test('malformed backup is rejected without changing existing progress',async()=>{const a=env(fixture);await a.api.ready;await assert.rejects(a.api.importBackup({storage:{studyCount:'999',topikExamResults:'broken'}}));assert.equal(a.storage.getItem('studyCount'),'12');assert.equal(a.storage.getItem('topikExamResults'),fixture.topikExamResults)});
test('unknown-only backup is rejected',async()=>{const a=env(fixture);await a.api.ready;await assert.rejects(a.api.importBackup({storage:{unrelated:'oops'}}));});
test('partial import write failure rolls back already-written fields',async()=>{const a=env(fixture);await a.api.ready;a.setFail('topikExamResults');await assert.rejects(a.api.importBackup({storage:{studyCount:'99',topikExamResults:fixture.topikExamResults}}));assert.equal(a.storage.getItem('studyCount'),'12')});
test('legacy vocabulary backup imports without losing exam results',async()=>{const a=env(fixture);await a.api.ready;const old={version:2,data:{words:{v2:{correct:2,wrong:0}},sessions:{},history:{}}};await a.api.importBackup(old);assert.equal(JSON.parse(a.storage.getItem('topikVocabState')).words.v2.correct,2);assert.equal(a.storage.getItem('topikExamResults'),fixture.topikExamResults)});
test('quota failure records no answer and displays a save warning',async()=>{const a=env();await a.api.ready;a.setFail('topikActivityStats');a.api.recordAnswer(true);assert.equal(a.storage.getItem('topikActivityStats'),null);assert(a.notices.some(n=>n.id==='learning-save-error'&&n.textContent.includes('保存できません')))});
test('valid JSON with invalid record shape is rejected',async()=>{const a=env(fixture);await a.api.ready;await assert.rejects(a.api.importBackup({storage:{topikExamResults:'{"records":null}'}}));assert.equal(a.storage.getItem('topikExamResults'),fixture.topikExamResults)});
